# Generated by Django 2.2.6 on 2019-11-02 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=50, verbose_name='Полное имя')),
            ],
        ),
        migrations.CreateModel(
            name='Flat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='Номер квартиры')),
                ('active', models.BooleanField(verbose_name='Дежурит?')),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='duty.Person', verbose_name='Жилец')),
            ],
        ),
    ]
