# Generated by Django 2.2.6 on 2019-11-03 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Название улицы')),
            ],
        ),
        migrations.AlterModelOptions(
            name='flat',
            options={'verbose_name': 'Квартира', 'verbose_name_plural': 'Квартиры'},
        ),
        migrations.AlterModelOptions(
            name='person',
            options={'verbose_name': 'Жилец', 'verbose_name_plural': 'Жильцы'},
        ),
        migrations.AddField(
            model_name='flat',
            name='entrance',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Номер квартиры'),
        ),
        migrations.AddField(
            model_name='flat',
            name='home_number',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True, verbose_name='Номер дома'),
        ),
        migrations.AddField(
            model_name='flat',
            name='street',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duty.Street', verbose_name='Улица'),
        ),
    ]
