# Generated by Django 2.2.6 on 2019-11-08 03:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0002_auto_20191103_1313'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='street',
            options={'verbose_name': 'улица', 'verbose_name_plural': 'улицы'},
        ),
        migrations.RemoveField(
            model_name='flat',
            name='home_number',
        ),
        migrations.RemoveField(
            model_name='flat',
            name='street',
        ),
        migrations.AlterField(
            model_name='flat',
            name='entrance',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Номер подьезда'),
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('home_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер дома')),
                ('street', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='duty.Street', verbose_name='Улица')),
            ],
        ),
        migrations.AddField(
            model_name='flat',
            name='address',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='duty.Address', verbose_name='Адрес'),
        ),
    ]
