# Generated by Django 2.2.6 on 2019-11-12 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('duty', '0004_auto_20191108_0657'),
    ]

    operations = [
        migrations.AddField(
            model_name='flat',
            name='sqare',
            field=models.FloatField(blank=True, null=True, verbose_name='Площадь квартиры'),
        ),
    ]
